---
- name: Create auth users
  sudo: true
  user: >
    name="{{ item.name }}"
    comment="{{ item.comment | default(item.name) }}"
    group="{{ item.group | default(omit) }}"
    groups="{{ item.groups | default(omit) }}"
    home="{{ item.home | default(omit) }}"
  with_items: auth_users
